### ISSUE TITLE
convert extension to WebExtension

### ISSUE THREAD

**Issue by lidel** [mozilla/moz-handler#10]
I see it uses old, deprecated SDK right now.
Is it possible to rewrite it as WebExtension?
Or do we need to wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1271553 ?

**Comment by mykmelez** [comment]
> Or do we need to wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1271553 ?

Yes, we'll need to wait for that API to become available, as there isn't a way to do this in a WebExtension currently.
