### ISSUE TITLE
This is the wrong way to handle it

### ISSUE THREAD

**Issue by Narvey** [mozilla/moz-handler#14]
If you are going to be bold enough to put a logo on your site that looks like it has a brand new application layer protocol on it, you need to be bold enough to actually make that protocol, not just jerry-rig it inside an addon or even (now) inside the browser code itself.

Also note that because of this oversight, people who buy new computers can't use moz://a to download Firefox, you have to already have Firefox (thus branding that only works for those who are already customers... oops).

**Comment by mykmelez** [comment]
Hi @Narvey, this repository isn't monitored by Mozilla leadership, the Mozilla brand team, or others who might be able to consider and respond to your criticisms. You might try posting them to one of the [Mozilla discussion forums](https://www.mozilla.org/en-US/about/forums/) instead.
